/*
 * Copyright 2006-2016 CIRDLES.org.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.cirdles.ambapo.userInterface;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import org.cirdles.ambapo.Ambapo;
/**
 *
 * @author evc1996
 */
public class AboutBox extends javax.swing.JDialog {
    
    private final static JDialog INSTANCE = new AboutBox(null, true);

    /**
     * Creates new form AboutBox
     *
     * @param parent
     * @param modal
     */
    private AboutBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initInstance();
        
    }

    private void initInstance() {
        setSizeAndCenter(400, 400);
        versionLabel.setText(Ambapo.VERSION);
        buildDateLabel.setText(Ambapo.RELEASE_DATE);
    }
    
    public static JDialog getInstance() {
        return INSTANCE;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        versionLabel = new javax.swing.JLabel();
        buildDateLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("AppleGothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(130, 15, 15));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ambapo");
        jLayeredPane2.add(jLabel1);
        jLabel1.setBounds(80, 20, 220, 50);

        jLabel2.setForeground(new java.awt.Color(130, 15, 15));
        jLabel2.setText("<html><b>Warranty:</b> Ambapo is provided as free open source software on an `as-is' basis.  Use at your own risk.  The developers disclaim all warranties about Ambapo.</html>");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(90, 200, 200, 110);

        jButton1.setText("GitHub");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton1);
        jButton1.setBounds(130, 140, 110, 40);

        versionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(130, 15, 15));
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionLabel.setText("Ambapo");
        jLayeredPane2.add(versionLabel);
        versionLabel.setBounds(90, 80, 190, 22);

        buildDateLabel.setForeground(new java.awt.Color(130, 15, 15));
        buildDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildDateLabel.setText("Ambapo");
        jLayeredPane2.add(buildDateLabel);
        buildDateLabel.setBounds(80, 110, 210, 16);

        getContentPane().add(jLayeredPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BrowserControl.showURI("https://github.com/CIRDLES/Ambapo");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void setSizeAndCenter(int preferredWidth, int preferredHeight) {
        super.setSize(preferredWidth, preferredHeight);
        super.setPreferredSize(new Dimension(preferredWidth, preferredHeight));

        //Get the screen size
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        //Calculate the frame location
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        //Set the new frame location centered
        setLocation(x, y);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            AboutBox dialog = new AboutBox(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
        
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buildDateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
