/*
 * Copyright 2006-2016 CIRDLES.org.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.cirdles.ambapo.userInterface;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import org.cirdles.ambapo.Ambapo;
/**
 *
 * @author evc1996
 */
public class AboutBox extends javax.swing.JDialog {
    
   private final static JDialog INSTANCE = new AboutBox(null, true);

    /**
     * Creates new form AboutBox
     *
     * @param parent
     * @param modal
     */
    private AboutBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initInstance();
        
    }

    private void initInstance() {
        setSizeAndCenter(400, 400);
        versionLabel.setText(Ambapo.VERSION);
        buildDateLabel.setText(Ambapo.RELEASE_DATE);
    }

    public static JDialog getInstance() {
        return INSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        versionLabel = new javax.swing.JLabel();
        gitHubButton = new javax.swing.JButton();
        ambapoLabel = new javax.swing.JLabel();
        contributorLabel = new javax.swing.JLabel();
        warrantyLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(400, 400));
        jLayeredPane1.setSize(new java.awt.Dimension(400, 400));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setSize(new java.awt.Dimension(400, 400));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        versionLabel.setBackground(new java.awt.Color(255, 255, 255));
        versionLabel.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(130, 15, 15));
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionLabel.setText("v. 0.1.0");
        versionLabel.setOpaque(true);
        jLayeredPane1.add(versionLabel);
        versionLabel.setBounds(100, 60, 160, 40);

        gitHubButton.setFont(new java.awt.Font("Shree Devanagari 714", 0, 16)); // NOI18N
        gitHubButton.setText("GitHub");
        gitHubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gitHubButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(gitHubButton);
        gitHubButton.setBounds(100, 109, 160, 40);

        ambapoLabel.setBackground(new java.awt.Color(255, 255, 255));
        ambapoLabel.setFont(new java.awt.Font("AppleGothic", 0, 36)); // NOI18N
        ambapoLabel.setForeground(new java.awt.Color(130, 15, 15));
        ambapoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ambapoLabel.setText("Ambapo");
        ambapoLabel.setOpaque(true);
        jLayeredPane1.add(ambapoLabel);
        ambapoLabel.setBounds(100, 10, 160, 60);

        contributorLabel.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        contributorLabel.setForeground(new java.awt.Color(130, 15, 15));
        contributorLabel.setText("Contributors: Elaina Cole, James Bowring");
        jLayeredPane1.add(contributorLabel);
        contributorLabel.setBounds(60, 170, 260, 50);

        warrantyLabel.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        warrantyLabel.setForeground(new java.awt.Color(130, 15, 15));
        warrantyLabel.setText("<html><b>Warranty:</b> Ambapo is provided as free open source software on an `as-is' basis.  Use at your own risk.  The developers disclaim all warranties about Ambapo.</html>");
        jLayeredPane1.add(warrantyLabel);
        warrantyLabel.setBounds(60, 220, 270, 100);

        add(jLayeredPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void gitHubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gitHubButtonActionPerformed
        // TODO add your handling code here:
        BrowserControl.showURI("https://github.com/bowring/Ambapo");
    }//GEN-LAST:event_gitHubButtonActionPerformed

    private void setSizeAndCenter(int preferredWidth, int preferredHeight) {
        super.setSize(preferredWidth, preferredHeight);
        super.setPreferredSize(new Dimension(preferredWidth, preferredHeight));

        //Get the screen size
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        //Calculate the frame location
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        //Set the new frame location centered
        setLocation(x, y);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ambapoLabel;
    private javax.swing.JLabel contributorLabel;
    private javax.swing.JButton gitHubButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel warrantyLabel;
    // End of variables declaration//GEN-END:variables
}
