/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cirdles.ambapo.userInterface;

import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import org.cirdles.ambapo.AmbapoFileFilter;
import org.cirdles.ambapo.ConversionFileHandler;

/**
 *
 * @author evc1996
 */
public class AmbapoUI extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    
    public int zonenumber_val;
    public char zoneletter_val;
    public char hemisphere_val;
    public BigDecimal easting_val;
    public BigDecimal northing_val;
    public BigDecimal longitude_val;
    public BigDecimal latitude_val;
    
    public ConversionFileHandler conversionFileHandler;
    
    public boolean toLatLong;
    public boolean toUTM;
    public boolean fromLatLong;
    public boolean fromUTM;
    
    public String toDatum;
    

    /**
     * Creates new customizer AmbapoUI
     */
    public AmbapoUI(ConversionFileHandler conversionFileHandler) {
        this.conversionFileHandler = conversionFileHandler;
        initComponents();
        //initUI();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        zoneNumber = new javax.swing.JTextField();
        easting = new javax.swing.JTextField();
        northing = new javax.swing.JTextField();
        zoneLetter = new javax.swing.JTextField();
        hemisphere = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        datumBulkConvert = new javax.swing.JComboBox();
        latitude = new javax.swing.JTextField();
        longitude = new javax.swing.JTextField();
        bulkConvertButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        toUTMRadioButton = new javax.swing.JRadioButton();
        toLatLongRadioButton = new javax.swing.JRadioButton();
        inputfile = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        fromUTMRadioButton = new javax.swing.JRadioButton();
        fromLatLongRadioButton = new javax.swing.JRadioButton();
        datumSoloConvert = new javax.swing.JComboBox();
        soloConvertButton = new javax.swing.JButton();
        outputfile = new javax.swing.JTextField();
        exportFileButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("AppleGothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(130, 15, 15));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ambapo");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(200, 0, 160, 60);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Easting");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(30, 70, 60, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Northing");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(30, 100, 60, 16);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Hemisphere");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(240, 70, 80, 16);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Zone Letter");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(360, 70, 80, 16);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Zone Number");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(350, 100, 90, 16);

        zoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneNumberActionPerformed(evt);
            }
        });
        jLayeredPane1.add(zoneNumber);
        zoneNumber.setBounds(450, 100, 110, 20);

        easting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastingActionPerformed(evt);
            }
        });
        jLayeredPane1.add(easting);
        easting.setBounds(90, 70, 110, 20);

        northing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                northingActionPerformed(evt);
            }
        });
        jLayeredPane1.add(northing);
        northing.setBounds(90, 100, 110, 20);

        zoneLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneLetterActionPerformed(evt);
            }
        });
        jLayeredPane1.add(zoneLetter);
        zoneLetter.setBounds(450, 70, 110, 20);

        hemisphere.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "N", "S" }));
        hemisphere.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hemisphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hemisphereActionPerformed(evt);
            }
        });
        jLayeredPane1.add(hemisphere);
        hemisphere.setBounds(240, 100, 80, 20);

        jLabel10.setText("Latitude");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(40, 180, 51, 16);

        jLabel11.setText("Longitude");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(330, 180, 70, 16);

        datumBulkConvert.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Datum" }));
        datumBulkConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumBulkConvertActionPerformed(evt);
            }
        });
        jLayeredPane1.add(datumBulkConvert);
        datumBulkConvert.setBounds(240, 300, 100, 20);

        latitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latitudeActionPerformed(evt);
            }
        });
        jLayeredPane1.add(latitude);
        latitude.setBounds(110, 180, 130, 20);
        jLayeredPane1.add(longitude);
        longitude.setBounds(410, 180, 130, 20);

        bulkConvertButton.setText("Convert");
        bulkConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulkConvertButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(bulkConvertButton);
        bulkConvertButton.setBounds(240, 260, 93, 30);

        jLabel7.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("OR...");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(260, 220, 45, 16);

        jLabel8.setText("Input File");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(20, 250, 70, 16);

        toUTMRadioButton.setText("UTM");
        jLayeredPane1.add(toUTMRadioButton);
        toUTMRadioButton.setBounds(400, 300, 70, 20);

        toLatLongRadioButton.setText("LatLong");
        toLatLongRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLatLongRadioButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(toLatLongRadioButton);
        toLatLongRadioButton.setBounds(480, 300, 90, 20);

        inputfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputfileActionPerformed(evt);
            }
        });
        jLayeredPane1.add(inputfile);
        inputfile.setBounds(100, 270, 110, 28);

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(browseButton);
        browseButton.setBounds(10, 270, 90, 29);

        jLabel9.setText("Output File");
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(380, 250, 80, 16);

        fromUTMRadioButton.setText("UTM");
        jLayeredPane1.add(fromUTMRadioButton);
        fromUTMRadioButton.setBounds(20, 300, 70, 23);

        fromLatLongRadioButton.setText("LatLong");
        fromLatLongRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromLatLongRadioButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(fromLatLongRadioButton);
        fromLatLongRadioButton.setBounds(90, 300, 90, 23);

        datumSoloConvert.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Datum" }));
        datumSoloConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumSoloConvertActionPerformed(evt);
            }
        });
        jLayeredPane1.add(datumSoloConvert);
        datumSoloConvert.setBounds(330, 140, 96, 27);

        soloConvertButton.setText("Convert");
        soloConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloConvertButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(soloConvertButton);
        soloConvertButton.setBounds(150, 140, 93, 29);

        outputfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputfileActionPerformed(evt);
            }
        });
        jLayeredPane1.add(outputfile);
        outputfile.setBounds(470, 270, 120, 28);

        exportFileButton.setText("Export...");
        exportFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportFileButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(exportFileButton);
        exportFileButton.setBounds(370, 270, 97, 29);

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(aboutButton);
        aboutButton.setBounds(0, 0, 82, 29);

        jInternalFrame1.getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        add(jInternalFrame1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void zoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoneNumberActionPerformed

    private void eastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eastingActionPerformed

    private void northingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_northingActionPerformed

    private void zoneLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneLetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoneLetterActionPerformed

    private void hemisphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hemisphereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hemisphereActionPerformed

    private void datumBulkConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumBulkConvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datumBulkConvertActionPerformed

    private void latitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudeActionPerformed

    private void bulkConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulkConvertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulkConvertButtonActionPerformed

    private void toLatLongRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLatLongRadioButtonActionPerformed
        // TODO add your handling code here:
        toLatLong = true;
    }//GEN-LAST:event_toLatLongRadioButtonActionPerformed

    private void inputfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputfileActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        /*String dialogTitle,
            File locationIn,
            final String fileExtension,
            FileFilter nonMacFileFilter,
            boolean allowMultipleSelect,
            JFrame parentFrame*/
        
        File inputFileLocation = FileHelper.AllPlatformGetFile("Select file to convert",
                new File(conversionFileHandler.getCurrentFileLocationToConvert()), 
                "*.csv", new AmbapoFileFilter(), false, jLayeredPane1)[0];
        if (inputFileLocation != null) {
            try {
                conversionFileHandler.setCurrentFileLocation(inputFileLocation.getCanonicalPath());
                updateCurrentPrawnFileLocation();
            } catch (IOException iOException) {
            }
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void fromLatLongRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromLatLongRadioButtonActionPerformed
        // TODO add your handling code here:
        fromLatLong = true;
    }//GEN-LAST:event_fromLatLongRadioButtonActionPerformed

    private void datumSoloConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumSoloConvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datumSoloConvertActionPerformed

    private void soloConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soloConvertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soloConvertButtonActionPerformed

    private void outputfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputfileActionPerformed

    private void exportFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportFileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportFileButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
        AboutBox.getInstance().setVisible(true);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void updateCurrentPrawnFileLocation() {
        inputfile.setText(conversionFileHandler.getCurrentFileLocationToConvert());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton bulkConvertButton;
    private javax.swing.JComboBox datumBulkConvert;
    private javax.swing.JComboBox datumSoloConvert;
    private javax.swing.JTextField easting;
    private javax.swing.JButton exportFileButton;
    private javax.swing.JRadioButton fromLatLongRadioButton;
    private javax.swing.JRadioButton fromUTMRadioButton;
    private javax.swing.JComboBox hemisphere;
    private javax.swing.JTextField inputfile;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField latitude;
    private javax.swing.JTextField longitude;
    private javax.swing.JTextField northing;
    private javax.swing.JTextField outputfile;
    private javax.swing.JButton soloConvertButton;
    private javax.swing.JRadioButton toLatLongRadioButton;
    private javax.swing.JRadioButton toUTMRadioButton;
    private javax.swing.JTextField zoneLetter;
    private javax.swing.JTextField zoneNumber;
    // End of variables declaration//GEN-END:variables
}
